# Define the repositories to inspect
repositories:
  - colymba/GridFieldBulkEditingTools
  - lekoala/silverstripe-debugbar
  - silverstripe/comment-notifications
  - silverstripe/silverstripe-activedirectory
  - silverstripe/silverstripe-akismet
  - silverstripe/silverstripe-auditor
  - silverstripe/silverstripe-blog
  - silverstripe/silverstripe-admin
  - silverstripe/silverstripe-assets
  - silverstripe/silverstripe-asset-admin
  - silverstripe/silverstripe-campaign-admin
  - silverstripe/silverstripe-ckan-registry
  - silverstripe/silverstripe-cms
  - silverstripe/silverstripe-comments
  - silverstripe/silverstripe-config
  - silverstripe/silverstripe-content-widget
  - silverstripe/silverstripe-contentreview
  - silverstripe/silverstripe-dms
  - silverstripe/silverstripe-dms-cart
  - silverstripe/silverstripe-documentconverter
  - silverstripe/silverstripe-elemental-bannerblock
  - silverstripe/silverstripe-elemental-fileblock
  - silverstripe/silverstripe-elemental-blocks
  - silverstripe/silverstripe-environmentcheck
  - silverstripe/silverstripe-externallinks
  - silverstripe/silverstripe-framework
  - silverstripe/silverstripe-fulltextsearch
  - silverstripe/silverstripe-graphql
  - silverstripe/silverstripe-gridfieldqueuedexport
  - silverstripe/silverstripe-html5
  - silverstripe/silverstripe-hybridsessions
  - silverstripe/silverstripe-iframe
  - silverstripe/silverstripe-installer
  - silverstripe/silverstripe-ldap
  - silverstripe/silverstripe-login-forms
  - silverstripe/silverstripe-lumberjack
  - silverstripe/silverstripe-mimevalidator
  - silverstripe/silverstripe-mfa
  - silverstripe/silverstripe-realme
  - silverstripe/silverstripe-registry
  - silverstripe/silverstripe-reports
  - silverstripe/silverstripe-restfulserver
  - silverstripe/silverstripe-secureassets
  - silverstripe/silverstripe-security-extensions
  - silverstripe/silverstripe-securityreport
  - silverstripe/silverstripe-segment-field
  - silverstripe/silverstripe-selectupload
  - silverstripe/silverstripe-sharedraftcontent
  - silverstripe/silverstripe-siteconfig
  - silverstripe/silverstripe-sitewidecontent-report
  - silverstripe/silverstripe-spamprotection
  - silverstripe/silverstripe-spellcheck
  - silverstripe/silverstripe-subsites
  - silverstripe/silverstripe-taxonomy
  - silverstripe/silverstripe-textextraction
  - silverstripe/silverstripe-totp-authenticator
  - silverstripe/silverstripe-translatable
  - silverstripe/silverstripe-userforms
  - silverstripe/silverstripe-versioned
  - silverstripe/silverstripe-versioned-admin
  - silverstripe/silverstripe-versionfeed
  - silverstripe/silverstripe-webauthn-authenticator
  - silverstripe/silverstripe-widgets
  - symbiote/silverstripe-advancedworkflow
  - symbiote/silverstripe-gridfieldextensions
  - symbiote/silverstripe-multivaluefield
  - symbiote/silverstripe-queuedjobs
  - silverstripe/recipe-authoring-tools
  - silverstripe/recipe-blog
  - silverstripe/recipe-cms
  - silverstripe/recipe-collaboration
  - silverstripe/recipe-content-blocks
  - silverstripe/recipe-core
  - silverstripe/recipe-form-building
  - silverstripe/recipe-reporting-tools
  - silverstripe/recipe-services
  - tractorcow/silverstripe-fluent
  - tractorcow/silverstripe-proxy-db
  - bringyourownideas/silverstripe-maintenance
  - bringyourownideas/silverstripe-composer-update-checker
  - bringyourownideas/silverstripe-composer-security-checker
  - dnadesign/silverstripe-elemental
  - dnadesign/silverstripe-elemental-userforms
  - elliot-sawyer/totp-authenticator
  - silverstripe/cwp
  - silverstripe/cwp-core
  - silverstripe/cwp-pdfexport
  - silverstripe/cwp-search
  - silverstripe/cwp-recipe-basic
  - silverstripe/cwp-recipe-blog
  - silverstripe/cwp-recipe-kitchen-sink
  - silverstripe/cwp-recipe-core
  - silverstripe/cwp-recipe-cms
  - silverstripe/cwp-recipe-search
  - silverstripe/cwp-agencyextensions
  - silverstripe/cwp-installer
  - silverstripe/cwp-starter-theme
  - silverstripe/cwp-watea-theme
  - UndefinedOffset/SortableGridField
  - silverstripe/addons.silverstripe.org
  - silverstripe/doc.silverstripe.org
  - silverstripe/silverstripe-docsviewer
  - silverstripe/silverstripe-controllerpolicy
  - silverstripe/silverstripe-tagfield

# Branches that should be ignored from repositories:
# Note: Ensure floaty values are cast as strings
travis_branch_blacklist:
  lekoala/silverstripe-debugbar: ['1.0', '1.1']
  dnadesign/silverstripe-elemental: ['1.3', '1.4', '1.5', '1.6']
  tractorcow/silverstripe-fluent: ['3.1', '3.2', '3.7', '3.8']
  silverstripe/cwp: ['1.1', '1.2', '1.3', '1.4', '1.5', '1.6', '1.7', '1.8', '1.9']
  silverstripe/cwp-core: ['1.1', '1.2', '1.3', '1.4', '1.5', '1.6', '1.7', '1.8', '1.9']
  silverstripe/silverstripe-admin: ['master_new']
  silverstripe/silverstripe-blog: ['0.3', '0.4', '0.5', '0.6', '1.0', '2.0', '2.1', '2.2', '2.3', '3.0', '3.3']
  silverstripe/silverstripe-cms: ['2.4', '3.0', '3.1', '3.2', '3.3', '3.4', '3.5']
  silverstripe/silverstripe-comments: ['1.1', '1.2', '2.0']
  silverstripe/silverstripe-docsviewer: ['0.1', '0.2']
  silverstripe/silverstripe-framework: ['2.4', '3.0', '3.1', '3.2', '3.3', '3.4', '3.5']
  silverstripe/silverstripe-fulltextsearch: ['2.1', '2.2']
  silverstripe/recipe-blog: ['1.2']
  silverstripe/recipe-content-blocks: ['1.1']
  silverstripe/silverstripe-reports: ['1.0']
  silverstripe/silverstripe-restfulserver: ['2.0']
  silverstripe/silverstripe-sharedraftcontent: ['1.1', '1.2']
  silverstripe/silverstripe-siteconfig: ['3.1', '3.2', '3.3', '3.4', '3.5']
  silverstripe/silverstripe-spamprotection: ['0.4', '1.0', '1.1']
  silverstripe/silverstripe-subsites: ['0.3', '0.4', '0.5', '0.6', '1.0']
  silverstripe/silverstripe-tagfield: ['0.3', '0.4', '1.0', '1.2']
  silverstripe/silverstripe-translatable: ['1.0', '1.1', '2.0', '2.1', 'master']
  silverstripe/silverstripe-userforms: ['1.0', '0.5', '2.0', '3.1', '4.0', '4.1', '4.2']
  symbiote/silverstripe-gridfieldextensions: ['1.0', '1.1']

# Should repository slugs be stripped back to the last dash for labels?
strip_repo_slugs_for_labels: true
