version: '3.7'

services:
  dashboard:
    build:
      context: docker
    working_dir: /app
    init: true
    restart: always
    volumes:
      - '.:/app'
    ports:
      - '3030:3030'
    entrypoint:
      - /bin/bash
      - /app/docker/entrypoint.sh
    env_file: .env